# Generated by Django 4.2.5 on 2023-09-30 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('screen_recorder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordedScreen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('shareable_link', models.CharField(max_length=255, unique=True)),
                ('screen_recording', models.FileField(blank=True, null=True, upload_to='screen_recordings/')),
                ('audio_recording', models.FileField(blank=True, null=True, upload_to='screen_recordings/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
