# serializers.py
from rest_framework import serializers
from .models import RecordedScreen

class RecordedScreenSerializer(serializers.ModelSerializer):
    class Meta:
        model = RecordedScreen
        fields = ('id', 'timestamp', 'shareable_link', 'screen_recording', 'audio_recording')
        read_only_fields = ('id', 'timestamp', 'shareable_link')  # id and timestamp are generated by the system

    def create(self, validated_data):
        # You can add custom logic here if needed before creating the RecordedScreen instance
        return RecordedScreen.objects.create(**validated_data)
